---
apiVersion: v1
kind: Namespace
metadata:
  name: php-multi-deploy

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: php-multi-deploy
  name: laravel-app
data:
  APP_ENV: dev

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: php-multi-deploy
  name: laravel-app-env
data:
  APP_NAME: "Kuberbetes Laravel"
  APP_ENV: "production"
  APP_KEY: "base64:QozarhCzkrDT5+8bHe+r/1jSloZjtSLHjsDZTjN+tI0="
  APP_DEBUG: "false"
  APP_URL: "http://php-multi-deploy.local"
  LOG_CHANNEL: "stack"
  LOG_LEVEL: "debug"
  DB_CONNECTION: "mysql"
  DB_HOST: "127.0.0.1"
  DB_PORT: "3306"
  DB_DATABASE: "laraval"
  DB_USERNAME: "root"
  DB_PASSWORD: ""
  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "file"
  QUEUE_CONNECTION: "sync"
  SESSION_DRIVER: "file"
  SESSION_LIFETIME: "120"
  MEMCACHED_HOST: "127.0.0.1"
  REDIS_HOST: "127.0.0.1"
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: php-multi-deploy
  name: laravel-app-nginx
  labels:
    app: laravel-app-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app-nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: laravel-app-nginx
    spec:
      containers:
        - name: nginx
          image: ccr.ccs.tencentyun.com/yaxin-cn/k8s-laravel-app-nginx:multi-deploy
          imagePullPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: php-multi-deploy
  name: laravel-app-phpfpm
  labels:
    app: laravel-app-phpfpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app-phpfpm
  strategy: {}
  template:
    metadata:
      labels:
        app: laravel-app-phpfpm
    spec:
      containers:
        - name: php-fpm
          image: ccr.ccs.tencentyun.com/yaxin-cn/k8s-laravel-app-phpfpm:multi-deploy
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: laravel-app-env

---
apiVersion: v1
kind: Service
metadata:
  namespace: php-multi-deploy
  name: laravel-app-phpfpm
spec:
  type: ClusterIP
  ports:
    - name: fastcgi
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: laravel-app-phpfpm

---
apiVersion: v1
kind: Service
metadata:
  namespace: php-multi-deploy
  name: laravel-app-nginx
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: laravel-app-nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: php-multi-deploy
  name: laravel-app
spec:
  rules:
  - host: php-multi-deploy.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: laravel-app-nginx
            port:
              number: 80
